# Generated by Django 4.1.4 on 2022-12-27 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
