# Generated by Django 4.1.4 on 2022-12-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
