# Generated by Django 4.1.4 on 2022-12-21 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='code',
        ),
    ]
