# Generated by Django 4.1.4 on 2022-12-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='username',
            field=models.TextField(default='boomkablamo'),
            preserve_default=False,
        ),
    ]
